// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: nist_sp800_90b.proto

package nistsp80090bv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Sp80090bAssessmentRequest contains the entropy source data and assessment parameters.
type Sp80090BAssessmentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw entropy samples packed into bytes.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// Number of bits per symbol (1-8, inclusive).
	BitsPerSymbol uint32 `protobuf:"varint,2,opt,name=bits_per_symbol,json=bitsPerSymbol,proto3" json:"bits_per_symbol,omitempty"`
	// If true, run IID (Independent and Identically Distributed) tests.
	IidMode bool `protobuf:"varint,3,opt,name=iid_mode,json=iidMode,proto3" json:"iid_mode,omitempty"`
	// If true, run Non-IID estimators.
	NonIidMode bool `protobuf:"varint,4,opt,name=non_iid_mode,json=nonIidMode,proto3" json:"non_iid_mode,omitempty"`
	// Verbosity level for output (0=quiet, 1=normal, 2=verbose, 3=debug).
	Verbosity     uint32 `protobuf:"varint,5,opt,name=verbosity,proto3" json:"verbosity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sp80090BAssessmentRequest) Reset() {
	*x = Sp80090BAssessmentRequest{}
	mi := &file_nist_sp800_90b_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sp80090BAssessmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sp80090BAssessmentRequest) ProtoMessage() {}

func (x *Sp80090BAssessmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nist_sp800_90b_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sp80090BAssessmentRequest.ProtoReflect.Descriptor instead.
func (*Sp80090BAssessmentRequest) Descriptor() ([]byte, []int) {
	return file_nist_sp800_90b_proto_rawDescGZIP(), []int{0}
}

func (x *Sp80090BAssessmentRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Sp80090BAssessmentRequest) GetBitsPerSymbol() uint32 {
	if x != nil {
		return x.BitsPerSymbol
	}
	return 0
}

func (x *Sp80090BAssessmentRequest) GetIidMode() bool {
	if x != nil {
		return x.IidMode
	}
	return false
}

func (x *Sp80090BAssessmentRequest) GetNonIidMode() bool {
	if x != nil {
		return x.NonIidMode
	}
	return false
}

func (x *Sp80090BAssessmentRequest) GetVerbosity() uint32 {
	if x != nil {
		return x.Verbosity
	}
	return 0
}

// Sp80090bAssessmentResponse contains the results of the NIST SP 800-90B entropy assessment.
type Sp80090BAssessmentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Minimum entropy estimate in bits per sample.
	MinEntropy float64 `protobuf:"fixed64,1,opt,name=min_entropy,json=minEntropy,proto3" json:"min_entropy,omitempty"`
	// Results from IID tests (if iid_mode was true).
	IidResults []*Sp80090BEstimatorResult `protobuf:"bytes,2,rep,name=iid_results,json=iidResults,proto3" json:"iid_results,omitempty"`
	// Results from Non-IID estimators (if non_iid_mode was true).
	NonIidResults []*Sp80090BEstimatorResult `protobuf:"bytes,3,rep,name=non_iid_results,json=nonIidResults,proto3" json:"non_iid_results,omitempty"`
	// Overall assessment result (true if data passes validation).
	Passed bool `protobuf:"varint,4,opt,name=passed,proto3" json:"passed,omitempty"`
	// Human-readable summary of the assessment.
	AssessmentSummary string `protobuf:"bytes,5,opt,name=assessment_summary,json=assessmentSummary,proto3" json:"assessment_summary,omitempty"`
	// Number of samples analyzed.
	SampleCount uint64 `protobuf:"varint,6,opt,name=sample_count,json=sampleCount,proto3" json:"sample_count,omitempty"`
	// Actual bits per symbol used in the assessment.
	BitsPerSymbol uint32 `protobuf:"varint,7,opt,name=bits_per_symbol,json=bitsPerSymbol,proto3" json:"bits_per_symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sp80090BAssessmentResponse) Reset() {
	*x = Sp80090BAssessmentResponse{}
	mi := &file_nist_sp800_90b_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sp80090BAssessmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sp80090BAssessmentResponse) ProtoMessage() {}

func (x *Sp80090BAssessmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nist_sp800_90b_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sp80090BAssessmentResponse.ProtoReflect.Descriptor instead.
func (*Sp80090BAssessmentResponse) Descriptor() ([]byte, []int) {
	return file_nist_sp800_90b_proto_rawDescGZIP(), []int{1}
}

func (x *Sp80090BAssessmentResponse) GetMinEntropy() float64 {
	if x != nil {
		return x.MinEntropy
	}
	return 0
}

func (x *Sp80090BAssessmentResponse) GetIidResults() []*Sp80090BEstimatorResult {
	if x != nil {
		return x.IidResults
	}
	return nil
}

func (x *Sp80090BAssessmentResponse) GetNonIidResults() []*Sp80090BEstimatorResult {
	if x != nil {
		return x.NonIidResults
	}
	return nil
}

func (x *Sp80090BAssessmentResponse) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *Sp80090BAssessmentResponse) GetAssessmentSummary() string {
	if x != nil {
		return x.AssessmentSummary
	}
	return ""
}

func (x *Sp80090BAssessmentResponse) GetSampleCount() uint64 {
	if x != nil {
		return x.SampleCount
	}
	return 0
}

func (x *Sp80090BAssessmentResponse) GetBitsPerSymbol() uint32 {
	if x != nil {
		return x.BitsPerSymbol
	}
	return 0
}

// Sp80090bEstimatorResult contains the result of a single NIST SP 800-90B estimator or test.
type Sp80090BEstimatorResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the estimator or test (e.g., "Most Common Value", "Collision Test").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Entropy estimate in bits per sample.
	EntropyEstimate float64 `protobuf:"fixed64,2,opt,name=entropy_estimate,json=entropyEstimate,proto3" json:"entropy_estimate,omitempty"`
	// Whether this test/estimator passed.
	Passed bool `protobuf:"varint,3,opt,name=passed,proto3" json:"passed,omitempty"`
	// Additional test-specific metrics and details.
	Details map[string]float64 `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	// Human-readable description of the result.
	Description   string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sp80090BEstimatorResult) Reset() {
	*x = Sp80090BEstimatorResult{}
	mi := &file_nist_sp800_90b_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sp80090BEstimatorResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sp80090BEstimatorResult) ProtoMessage() {}

func (x *Sp80090BEstimatorResult) ProtoReflect() protoreflect.Message {
	mi := &file_nist_sp800_90b_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sp80090BEstimatorResult.ProtoReflect.Descriptor instead.
func (*Sp80090BEstimatorResult) Descriptor() ([]byte, []int) {
	return file_nist_sp800_90b_proto_rawDescGZIP(), []int{2}
}

func (x *Sp80090BEstimatorResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Sp80090BEstimatorResult) GetEntropyEstimate() float64 {
	if x != nil {
		return x.EntropyEstimate
	}
	return 0
}

func (x *Sp80090BEstimatorResult) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *Sp80090BEstimatorResult) GetDetails() map[string]float64 {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *Sp80090BEstimatorResult) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_nist_sp800_90b_proto protoreflect.FileDescriptor

const file_nist_sp800_90b_proto_rawDesc = "" +
	"\n" +
	"\x14nist_sp800_90b.proto\x12\x11nist.sp800_90b.v1\"\xb2\x01\n" +
	"\x19Sp80090bAssessmentRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12&\n" +
	"\x0fbits_per_symbol\x18\x02 \x01(\rR\rbitsPerSymbol\x12\x19\n" +
	"\biid_mode\x18\x03 \x01(\bR\aiidMode\x12 \n" +
	"\fnon_iid_mode\x18\x04 \x01(\bR\n" +
	"nonIidMode\x12\x1c\n" +
	"\tverbosity\x18\x05 \x01(\rR\tverbosity\"\xf0\x02\n" +
	"\x1aSp80090bAssessmentResponse\x12\x1f\n" +
	"\vmin_entropy\x18\x01 \x01(\x01R\n" +
	"minEntropy\x12K\n" +
	"\viid_results\x18\x02 \x03(\v2*.nist.sp800_90b.v1.Sp80090bEstimatorResultR\n" +
	"iidResults\x12R\n" +
	"\x0fnon_iid_results\x18\x03 \x03(\v2*.nist.sp800_90b.v1.Sp80090bEstimatorResultR\rnonIidResults\x12\x16\n" +
	"\x06passed\x18\x04 \x01(\bR\x06passed\x12-\n" +
	"\x12assessment_summary\x18\x05 \x01(\tR\x11assessmentSummary\x12!\n" +
	"\fsample_count\x18\x06 \x01(\x04R\vsampleCount\x12&\n" +
	"\x0fbits_per_symbol\x18\a \x01(\rR\rbitsPerSymbol\"\xa1\x02\n" +
	"\x17Sp80090bEstimatorResult\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12)\n" +
	"\x10entropy_estimate\x18\x02 \x01(\x01R\x0fentropyEstimate\x12\x16\n" +
	"\x06passed\x18\x03 \x01(\bR\x06passed\x12Q\n" +
	"\adetails\x18\x04 \x03(\v27.nist.sp800_90b.v1.Sp80090bEstimatorResult.DetailsEntryR\adetails\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x012\x89\x01\n" +
	"\x19Sp80090bAssessmentService\x12l\n" +
	"\rAssessEntropy\x12,.nist.sp800_90b.v1.Sp80090bAssessmentRequest\x1a-.nist.sp800_90b.v1.Sp80090bAssessmentResponseB?Z=github.com/AmmannChristian/nist-800-90b/pkg/pb;nistsp80090bv1b\x06proto3"

var (
	file_nist_sp800_90b_proto_rawDescOnce sync.Once
	file_nist_sp800_90b_proto_rawDescData []byte
)

func file_nist_sp800_90b_proto_rawDescGZIP() []byte {
	file_nist_sp800_90b_proto_rawDescOnce.Do(func() {
		file_nist_sp800_90b_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nist_sp800_90b_proto_rawDesc), len(file_nist_sp800_90b_proto_rawDesc)))
	})
	return file_nist_sp800_90b_proto_rawDescData
}

var file_nist_sp800_90b_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_nist_sp800_90b_proto_goTypes = []any{
	(*Sp80090BAssessmentRequest)(nil),  // 0: nist.sp800_90b.v1.Sp80090bAssessmentRequest
	(*Sp80090BAssessmentResponse)(nil), // 1: nist.sp800_90b.v1.Sp80090bAssessmentResponse
	(*Sp80090BEstimatorResult)(nil),    // 2: nist.sp800_90b.v1.Sp80090bEstimatorResult
	nil,                                // 3: nist.sp800_90b.v1.Sp80090bEstimatorResult.DetailsEntry
}
var file_nist_sp800_90b_proto_depIdxs = []int32{
	2, // 0: nist.sp800_90b.v1.Sp80090bAssessmentResponse.iid_results:type_name -> nist.sp800_90b.v1.Sp80090bEstimatorResult
	2, // 1: nist.sp800_90b.v1.Sp80090bAssessmentResponse.non_iid_results:type_name -> nist.sp800_90b.v1.Sp80090bEstimatorResult
	3, // 2: nist.sp800_90b.v1.Sp80090bEstimatorResult.details:type_name -> nist.sp800_90b.v1.Sp80090bEstimatorResult.DetailsEntry
	0, // 3: nist.sp800_90b.v1.Sp80090bAssessmentService.AssessEntropy:input_type -> nist.sp800_90b.v1.Sp80090bAssessmentRequest
	1, // 4: nist.sp800_90b.v1.Sp80090bAssessmentService.AssessEntropy:output_type -> nist.sp800_90b.v1.Sp80090bAssessmentResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_nist_sp800_90b_proto_init() }
func file_nist_sp800_90b_proto_init() {
	if File_nist_sp800_90b_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nist_sp800_90b_proto_rawDesc), len(file_nist_sp800_90b_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nist_sp800_90b_proto_goTypes,
		DependencyIndexes: file_nist_sp800_90b_proto_depIdxs,
		MessageInfos:      file_nist_sp800_90b_proto_msgTypes,
	}.Build()
	File_nist_sp800_90b_proto = out.File
	file_nist_sp800_90b_proto_goTypes = nil
	file_nist_sp800_90b_proto_depIdxs = nil
}
