// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: nist_sp800_90b.proto

package nistsp80090bv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Sp80090BAssessmentService_AssessEntropy_FullMethodName = "/nist.sp800_90b.v1.Sp80090bAssessmentService/AssessEntropy"
)

// Sp80090BAssessmentServiceClient is the client API for Sp80090BAssessmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for NIST SP 800-90B entropy assessment
type Sp80090BAssessmentServiceClient interface {
	// AssessEntropy performs NIST SP 800-90B entropy assessment on the provided data samples.
	AssessEntropy(ctx context.Context, in *Sp80090BAssessmentRequest, opts ...grpc.CallOption) (*Sp80090BAssessmentResponse, error)
}

type sp80090BAssessmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSp80090BAssessmentServiceClient(cc grpc.ClientConnInterface) Sp80090BAssessmentServiceClient {
	return &sp80090BAssessmentServiceClient{cc}
}

func (c *sp80090BAssessmentServiceClient) AssessEntropy(ctx context.Context, in *Sp80090BAssessmentRequest, opts ...grpc.CallOption) (*Sp80090BAssessmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Sp80090BAssessmentResponse)
	err := c.cc.Invoke(ctx, Sp80090BAssessmentService_AssessEntropy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Sp80090BAssessmentServiceServer is the server API for Sp80090BAssessmentService service.
// All implementations must embed UnimplementedSp80090BAssessmentServiceServer
// for forward compatibility.
//
// Service for NIST SP 800-90B entropy assessment
type Sp80090BAssessmentServiceServer interface {
	// AssessEntropy performs NIST SP 800-90B entropy assessment on the provided data samples.
	AssessEntropy(context.Context, *Sp80090BAssessmentRequest) (*Sp80090BAssessmentResponse, error)
	mustEmbedUnimplementedSp80090BAssessmentServiceServer()
}

// UnimplementedSp80090BAssessmentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSp80090BAssessmentServiceServer struct{}

func (UnimplementedSp80090BAssessmentServiceServer) AssessEntropy(context.Context, *Sp80090BAssessmentRequest) (*Sp80090BAssessmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssessEntropy not implemented")
}
func (UnimplementedSp80090BAssessmentServiceServer) mustEmbedUnimplementedSp80090BAssessmentServiceServer() {
}
func (UnimplementedSp80090BAssessmentServiceServer) testEmbeddedByValue() {}

// UnsafeSp80090BAssessmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Sp80090BAssessmentServiceServer will
// result in compilation errors.
type UnsafeSp80090BAssessmentServiceServer interface {
	mustEmbedUnimplementedSp80090BAssessmentServiceServer()
}

func RegisterSp80090BAssessmentServiceServer(s grpc.ServiceRegistrar, srv Sp80090BAssessmentServiceServer) {
	// If the following call panics, it indicates UnimplementedSp80090BAssessmentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Sp80090BAssessmentService_ServiceDesc, srv)
}

func _Sp80090BAssessmentService_AssessEntropy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Sp80090BAssessmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Sp80090BAssessmentServiceServer).AssessEntropy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sp80090BAssessmentService_AssessEntropy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Sp80090BAssessmentServiceServer).AssessEntropy(ctx, req.(*Sp80090BAssessmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Sp80090BAssessmentService_ServiceDesc is the grpc.ServiceDesc for Sp80090BAssessmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sp80090BAssessmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nist.sp800_90b.v1.Sp80090bAssessmentService",
	HandlerType: (*Sp80090BAssessmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssessEntropy",
			Handler:    _Sp80090BAssessmentService_AssessEntropy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nist_sp800_90b.proto",
}
