// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EntropyService_AssessEntropy_FullMethodName = "/nist.v1.EntropyService/AssessEntropy"
)

// EntropyServiceClient is the client API for EntropyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EntropyService provides NIST SP 800-90B entropy assessment for entropy sources.
type EntropyServiceClient interface {
	// AssessEntropy performs entropy assessment on the provided data samples.
	// Supports both IID (Independent and Identically Distributed) tests and
	// Non-IID estimators as specified in NIST SP 800-90B.
	AssessEntropy(ctx context.Context, in *EntropyAssessmentRequest, opts ...grpc.CallOption) (*EntropyAssessmentResponse, error)
}

type entropyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEntropyServiceClient(cc grpc.ClientConnInterface) EntropyServiceClient {
	return &entropyServiceClient{cc}
}

func (c *entropyServiceClient) AssessEntropy(ctx context.Context, in *EntropyAssessmentRequest, opts ...grpc.CallOption) (*EntropyAssessmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EntropyAssessmentResponse)
	err := c.cc.Invoke(ctx, EntropyService_AssessEntropy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EntropyServiceServer is the server API for EntropyService service.
// All implementations must embed UnimplementedEntropyServiceServer
// for forward compatibility.
//
// EntropyService provides NIST SP 800-90B entropy assessment for entropy sources.
type EntropyServiceServer interface {
	// AssessEntropy performs entropy assessment on the provided data samples.
	// Supports both IID (Independent and Identically Distributed) tests and
	// Non-IID estimators as specified in NIST SP 800-90B.
	AssessEntropy(context.Context, *EntropyAssessmentRequest) (*EntropyAssessmentResponse, error)
	mustEmbedUnimplementedEntropyServiceServer()
}

// UnimplementedEntropyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEntropyServiceServer struct{}

func (UnimplementedEntropyServiceServer) AssessEntropy(context.Context, *EntropyAssessmentRequest) (*EntropyAssessmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssessEntropy not implemented")
}
func (UnimplementedEntropyServiceServer) mustEmbedUnimplementedEntropyServiceServer() {}
func (UnimplementedEntropyServiceServer) testEmbeddedByValue()                        {}

// UnsafeEntropyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EntropyServiceServer will
// result in compilation errors.
type UnsafeEntropyServiceServer interface {
	mustEmbedUnimplementedEntropyServiceServer()
}

func RegisterEntropyServiceServer(s grpc.ServiceRegistrar, srv EntropyServiceServer) {
	// If the following call panics, it indicates UnimplementedEntropyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EntropyService_ServiceDesc, srv)
}

func _EntropyService_AssessEntropy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntropyAssessmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntropyServiceServer).AssessEntropy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntropyService_AssessEntropy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntropyServiceServer).AssessEntropy(ctx, req.(*EntropyAssessmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EntropyService_ServiceDesc is the grpc.ServiceDesc for EntropyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EntropyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nist.v1.EntropyService",
	HandlerType: (*EntropyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssessEntropy",
			Handler:    _EntropyService_AssessEntropy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
