// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EntropyAssessmentRequest contains the entropy source data and assessment parameters.
type EntropyAssessmentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw entropy samples packed into bytes.
	// Samples are assumed to be packed into 8-bit values, where the least
	// significant 'bits_per_symbol' bits constitute the symbol.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// Number of bits per symbol (1-8, inclusive).
	// For example, 8 for byte-level analysis, 1 for binary data.
	BitsPerSymbol uint32 `protobuf:"varint,2,opt,name=bits_per_symbol,json=bitsPerSymbol,proto3" json:"bits_per_symbol,omitempty"`
	// If true, run IID (Independent and Identically Distributed) tests.
	// IID tests include permutation tests and chi-square tests.
	IidMode bool `protobuf:"varint,3,opt,name=iid_mode,json=iidMode,proto3" json:"iid_mode,omitempty"`
	// If true, run Non-IID estimators.
	// Non-IID estimators include MCV, Collision, Markov, Compression, etc.
	NonIidMode bool `protobuf:"varint,4,opt,name=non_iid_mode,json=nonIidMode,proto3" json:"non_iid_mode,omitempty"`
	// Verbosity level for output (0=quiet, 1=normal, 2=verbose, 3=debug).
	Verbosity     uint32 `protobuf:"varint,5,opt,name=verbosity,proto3" json:"verbosity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntropyAssessmentRequest) Reset() {
	*x = EntropyAssessmentRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntropyAssessmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntropyAssessmentRequest) ProtoMessage() {}

func (x *EntropyAssessmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntropyAssessmentRequest.ProtoReflect.Descriptor instead.
func (*EntropyAssessmentRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *EntropyAssessmentRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *EntropyAssessmentRequest) GetBitsPerSymbol() uint32 {
	if x != nil {
		return x.BitsPerSymbol
	}
	return 0
}

func (x *EntropyAssessmentRequest) GetIidMode() bool {
	if x != nil {
		return x.IidMode
	}
	return false
}

func (x *EntropyAssessmentRequest) GetNonIidMode() bool {
	if x != nil {
		return x.NonIidMode
	}
	return false
}

func (x *EntropyAssessmentRequest) GetVerbosity() uint32 {
	if x != nil {
		return x.Verbosity
	}
	return 0
}

// EntropyAssessmentResponse contains the results of the entropy assessment.
type EntropyAssessmentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Minimum entropy estimate in bits per sample.
	// This is the most conservative estimate across all tests/estimators.
	MinEntropy float64 `protobuf:"fixed64,1,opt,name=min_entropy,json=minEntropy,proto3" json:"min_entropy,omitempty"`
	// Results from IID tests (if iid_mode was true).
	IidResults []*EstimatorResult `protobuf:"bytes,2,rep,name=iid_results,json=iidResults,proto3" json:"iid_results,omitempty"`
	// Results from Non-IID estimators (if non_iid_mode was true).
	NonIidResults []*EstimatorResult `protobuf:"bytes,3,rep,name=non_iid_results,json=nonIidResults,proto3" json:"non_iid_results,omitempty"`
	// Overall assessment result (true if data passes validation).
	Passed bool `protobuf:"varint,4,opt,name=passed,proto3" json:"passed,omitempty"`
	// Human-readable summary of the assessment.
	AssessmentSummary string `protobuf:"bytes,5,opt,name=assessment_summary,json=assessmentSummary,proto3" json:"assessment_summary,omitempty"`
	// Number of samples analyzed.
	SampleCount uint64 `protobuf:"varint,6,opt,name=sample_count,json=sampleCount,proto3" json:"sample_count,omitempty"`
	// Actual bits per symbol used in the assessment.
	BitsPerSymbol uint32 `protobuf:"varint,7,opt,name=bits_per_symbol,json=bitsPerSymbol,proto3" json:"bits_per_symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntropyAssessmentResponse) Reset() {
	*x = EntropyAssessmentResponse{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntropyAssessmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntropyAssessmentResponse) ProtoMessage() {}

func (x *EntropyAssessmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntropyAssessmentResponse.ProtoReflect.Descriptor instead.
func (*EntropyAssessmentResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *EntropyAssessmentResponse) GetMinEntropy() float64 {
	if x != nil {
		return x.MinEntropy
	}
	return 0
}

func (x *EntropyAssessmentResponse) GetIidResults() []*EstimatorResult {
	if x != nil {
		return x.IidResults
	}
	return nil
}

func (x *EntropyAssessmentResponse) GetNonIidResults() []*EstimatorResult {
	if x != nil {
		return x.NonIidResults
	}
	return nil
}

func (x *EntropyAssessmentResponse) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *EntropyAssessmentResponse) GetAssessmentSummary() string {
	if x != nil {
		return x.AssessmentSummary
	}
	return ""
}

func (x *EntropyAssessmentResponse) GetSampleCount() uint64 {
	if x != nil {
		return x.SampleCount
	}
	return 0
}

func (x *EntropyAssessmentResponse) GetBitsPerSymbol() uint32 {
	if x != nil {
		return x.BitsPerSymbol
	}
	return 0
}

// EstimatorResult contains the result of a single estimator or test.
type EstimatorResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the estimator or test (e.g., "Most Common Value", "Collision Test").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Entropy estimate in bits per sample.
	// For IID tests, this may be derived from the p-value.
	EntropyEstimate float64 `protobuf:"fixed64,2,opt,name=entropy_estimate,json=entropyEstimate,proto3" json:"entropy_estimate,omitempty"`
	// Whether this test/estimator passed (true) or failed (false).
	// For IID tests, typically based on p-value >= 0.0001.
	Passed bool `protobuf:"varint,3,opt,name=passed,proto3" json:"passed,omitempty"`
	// Additional test-specific metrics and details.
	// May include p-values, test statistics, intermediate results, etc.
	Details map[string]float64 `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	// Human-readable description of the result.
	Description   string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstimatorResult) Reset() {
	*x = EstimatorResult{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstimatorResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimatorResult) ProtoMessage() {}

func (x *EstimatorResult) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimatorResult.ProtoReflect.Descriptor instead.
func (*EstimatorResult) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *EstimatorResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EstimatorResult) GetEntropyEstimate() float64 {
	if x != nil {
		return x.EntropyEstimate
	}
	return 0
}

func (x *EstimatorResult) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *EstimatorResult) GetDetails() map[string]float64 {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *EstimatorResult) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\anist.v1\"\xb1\x01\n" +
	"\x18EntropyAssessmentRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12&\n" +
	"\x0fbits_per_symbol\x18\x02 \x01(\rR\rbitsPerSymbol\x12\x19\n" +
	"\biid_mode\x18\x03 \x01(\bR\aiidMode\x12 \n" +
	"\fnon_iid_mode\x18\x04 \x01(\bR\n" +
	"nonIidMode\x12\x1c\n" +
	"\tverbosity\x18\x05 \x01(\rR\tverbosity\"\xcb\x02\n" +
	"\x19EntropyAssessmentResponse\x12\x1f\n" +
	"\vmin_entropy\x18\x01 \x01(\x01R\n" +
	"minEntropy\x129\n" +
	"\viid_results\x18\x02 \x03(\v2\x18.nist.v1.EstimatorResultR\n" +
	"iidResults\x12@\n" +
	"\x0fnon_iid_results\x18\x03 \x03(\v2\x18.nist.v1.EstimatorResultR\rnonIidResults\x12\x16\n" +
	"\x06passed\x18\x04 \x01(\bR\x06passed\x12-\n" +
	"\x12assessment_summary\x18\x05 \x01(\tR\x11assessmentSummary\x12!\n" +
	"\fsample_count\x18\x06 \x01(\x04R\vsampleCount\x12&\n" +
	"\x0fbits_per_symbol\x18\a \x01(\rR\rbitsPerSymbol\"\x87\x02\n" +
	"\x0fEstimatorResult\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12)\n" +
	"\x10entropy_estimate\x18\x02 \x01(\x01R\x0fentropyEstimate\x12\x16\n" +
	"\x06passed\x18\x03 \x01(\bR\x06passed\x12?\n" +
	"\adetails\x18\x04 \x03(\v2%.nist.v1.EstimatorResult.DetailsEntryR\adetails\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x012h\n" +
	"\x0eEntropyService\x12V\n" +
	"\rAssessEntropy\x12!.nist.v1.EntropyAssessmentRequest\x1a\".nist.v1.EntropyAssessmentResponseB0Z.github.com/AmmannChristian/nist-800-90b/pkg/pbb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_service_proto_goTypes = []any{
	(*EntropyAssessmentRequest)(nil),  // 0: nist.v1.EntropyAssessmentRequest
	(*EntropyAssessmentResponse)(nil), // 1: nist.v1.EntropyAssessmentResponse
	(*EstimatorResult)(nil),           // 2: nist.v1.EstimatorResult
	nil,                               // 3: nist.v1.EstimatorResult.DetailsEntry
}
var file_service_proto_depIdxs = []int32{
	2, // 0: nist.v1.EntropyAssessmentResponse.iid_results:type_name -> nist.v1.EstimatorResult
	2, // 1: nist.v1.EntropyAssessmentResponse.non_iid_results:type_name -> nist.v1.EstimatorResult
	3, // 2: nist.v1.EstimatorResult.details:type_name -> nist.v1.EstimatorResult.DetailsEntry
	0, // 3: nist.v1.EntropyService.AssessEntropy:input_type -> nist.v1.EntropyAssessmentRequest
	1, // 4: nist.v1.EntropyService.AssessEntropy:output_type -> nist.v1.EntropyAssessmentResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
